
name: My first workflow


on:
  push:
     branches : ["main"]
 
   

jobs:
  build:
  
    runs-on: ubuntu-latest

   
    steps:
 
      - uses: actions/checkout@v3
        name: Let's Checkout
        id: vars


      - name: Print test message
        run: echo Success!
        
      - name: Uses checkout output
        run: echo ${{steps.vars.outputs}}

    
