
name: My first workflow


on:
  push:
 
  pull_request:
   

jobs:
  build:
  
    runs-on: ubuntu-latest

   
    steps:
 
      - uses: actions/checkout@v3

    
      - name: Print test message
        run: echo Success!

    
